spring:
  application:
    name: tonpad
  datasource:
    url: jdbc:sqlite:src/main/resources/db/database.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: never

app:
  data-path: "basePath"
  reserved-names:
    templates-dir: "templates"
    notes-dir: "notes"
  js-functions-directory: classpath:js
  changelog-path: db/changelog/schema.sql